require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/acadamic_programs", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # AcadamicProgram. As you add validations to AcadamicProgram, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      AcadamicProgram.create! valid_attributes
      get acadamic_programs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      acadamic_program = AcadamicProgram.create! valid_attributes
      get acadamic_program_url(acadamic_program)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_acadamic_program_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      acadamic_program = AcadamicProgram.create! valid_attributes
      get edit_acadamic_program_url(acadamic_program)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AcadamicProgram" do
        expect {
          post acadamic_programs_url, params: { acadamic_program: valid_attributes }
        }.to change(AcadamicProgram, :count).by(1)
      end

      it "redirects to the created acadamic_program" do
        post acadamic_programs_url, params: { acadamic_program: valid_attributes }
        expect(response).to redirect_to(acadamic_program_url(AcadamicProgram.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AcadamicProgram" do
        expect {
          post acadamic_programs_url, params: { acadamic_program: invalid_attributes }
        }.to change(AcadamicProgram, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post acadamic_programs_url, params: { acadamic_program: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested acadamic_program" do
        acadamic_program = AcadamicProgram.create! valid_attributes
        patch acadamic_program_url(acadamic_program), params: { acadamic_program: new_attributes }
        acadamic_program.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the acadamic_program" do
        acadamic_program = AcadamicProgram.create! valid_attributes
        patch acadamic_program_url(acadamic_program), params: { acadamic_program: new_attributes }
        acadamic_program.reload
        expect(response).to redirect_to(acadamic_program_url(acadamic_program))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        acadamic_program = AcadamicProgram.create! valid_attributes
        patch acadamic_program_url(acadamic_program), params: { acadamic_program: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested acadamic_program" do
      acadamic_program = AcadamicProgram.create! valid_attributes
      expect {
        delete acadamic_program_url(acadamic_program)
      }.to change(AcadamicProgram, :count).by(-1)
    end

    it "redirects to the acadamic_programs list" do
      acadamic_program = AcadamicProgram.create! valid_attributes
      delete acadamic_program_url(acadamic_program)
      expect(response).to redirect_to(acadamic_programs_url)
    end
  end
end
