require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/acadamic_announcements", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # AcadamicAnnouncement. As you add validations to AcadamicAnnouncement, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      AcadamicAnnouncement.create! valid_attributes
      get acadamic_announcements_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      acadamic_announcement = AcadamicAnnouncement.create! valid_attributes
      get acadamic_announcement_url(acadamic_announcement)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_acadamic_announcement_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      acadamic_announcement = AcadamicAnnouncement.create! valid_attributes
      get edit_acadamic_announcement_url(acadamic_announcement)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AcadamicAnnouncement" do
        expect {
          post acadamic_announcements_url, params: { acadamic_announcement: valid_attributes }
        }.to change(AcadamicAnnouncement, :count).by(1)
      end

      it "redirects to the created acadamic_announcement" do
        post acadamic_announcements_url, params: { acadamic_announcement: valid_attributes }
        expect(response).to redirect_to(acadamic_announcement_url(AcadamicAnnouncement.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AcadamicAnnouncement" do
        expect {
          post acadamic_announcements_url, params: { acadamic_announcement: invalid_attributes }
        }.to change(AcadamicAnnouncement, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post acadamic_announcements_url, params: { acadamic_announcement: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested acadamic_announcement" do
        acadamic_announcement = AcadamicAnnouncement.create! valid_attributes
        patch acadamic_announcement_url(acadamic_announcement), params: { acadamic_announcement: new_attributes }
        acadamic_announcement.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the acadamic_announcement" do
        acadamic_announcement = AcadamicAnnouncement.create! valid_attributes
        patch acadamic_announcement_url(acadamic_announcement), params: { acadamic_announcement: new_attributes }
        acadamic_announcement.reload
        expect(response).to redirect_to(acadamic_announcement_url(acadamic_announcement))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        acadamic_announcement = AcadamicAnnouncement.create! valid_attributes
        patch acadamic_announcement_url(acadamic_announcement), params: { acadamic_announcement: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested acadamic_announcement" do
      acadamic_announcement = AcadamicAnnouncement.create! valid_attributes
      expect {
        delete acadamic_announcement_url(acadamic_announcement)
      }.to change(AcadamicAnnouncement, :count).by(-1)
    end

    it "redirects to the acadamic_announcements list" do
      acadamic_announcement = AcadamicAnnouncement.create! valid_attributes
      delete acadamic_announcement_url(acadamic_announcement)
      expect(response).to redirect_to(acadamic_announcements_url)
    end
  end
end
