require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/program_types", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ProgramType. As you add validations to ProgramType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ProgramType.create! valid_attributes
      get program_types_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      program_type = ProgramType.create! valid_attributes
      get program_type_url(program_type)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_program_type_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      program_type = ProgramType.create! valid_attributes
      get edit_program_type_url(program_type)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ProgramType" do
        expect {
          post program_types_url, params: { program_type: valid_attributes }
        }.to change(ProgramType, :count).by(1)
      end

      it "redirects to the created program_type" do
        post program_types_url, params: { program_type: valid_attributes }
        expect(response).to redirect_to(program_type_url(ProgramType.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ProgramType" do
        expect {
          post program_types_url, params: { program_type: invalid_attributes }
        }.to change(ProgramType, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post program_types_url, params: { program_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested program_type" do
        program_type = ProgramType.create! valid_attributes
        patch program_type_url(program_type), params: { program_type: new_attributes }
        program_type.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the program_type" do
        program_type = ProgramType.create! valid_attributes
        patch program_type_url(program_type), params: { program_type: new_attributes }
        program_type.reload
        expect(response).to redirect_to(program_type_url(program_type))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        program_type = ProgramType.create! valid_attributes
        patch program_type_url(program_type), params: { program_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested program_type" do
      program_type = ProgramType.create! valid_attributes
      expect {
        delete program_type_url(program_type)
      }.to change(ProgramType, :count).by(-1)
    end

    it "redirects to the program_types list" do
      program_type = ProgramType.create! valid_attributes
      delete program_type_url(program_type)
      expect(response).to redirect_to(program_types_url)
    end
  end
end
